apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "daadaadaa"
  description: "daadaa"
  annotations:
    github.com/project-slug: outesting/daadaadaa
    backstage.io/techdocs-ref: dir:.
    # instanceName and github-organization-project-name are optional. The value is a string and should be enclosed in double quotes ""
    jenkins.io/job-full-name: "techdocs"
    prometheus.io/alert: all
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
spec:
  type: repository
  lifecycle: experimental
  owner: "group:default/guests"
